server:
  port: 8080
  servlet:
    context-path: /api

spring:
  # MySQL 配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/nexus_brain
    username: root
    password: root
